// Lynceus T1 wire contract — extracted EXPLAIN plans.
//
// auto_explain writes a chosen statement's plan into the Postgres log. The
// collector parses that plan (JSON format) and emits the normalized records
// below. The SOURCE plan body is full of literals (Filter, Index Cond,
// Output, Query Text) and stays in the collector-local T2 LogPayload — it is
// never shipped here.
//
// INVARIANT: no field on QueryPlan or PlanNode may carry a query literal.
// Condition strings are normalized (literals -> $n) at the collector, and
// omitted entirely if normalization cannot prove they are literal-free.
// A contract test in internal/proto/lynceus/v1/contract_test.go enforces
// the field allowlist; adding a literal-bearing field fails the build.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/lynceus/v1/plan.proto

package lynceusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryPlan is one extracted auto_explain plan, normalized at the collector.
// Grain: per-execution-sample (captured when auto_explain fires for a
// statement), keyed to the statement by its normalized fingerprint.
type QueryPlan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fingerprint of the normalized statement this plan is for. Computed
	// collector-side from the statement text; the text itself never leaves.
	Fingerprint       string    `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	CapturedAtUnix    int64     `protobuf:"varint,2,opt,name=captured_at_unix,json=capturedAtUnix,proto3" json:"captured_at_unix,omitempty"`
	FormatVersion     int32     `protobuf:"varint,3,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`                  // plan extractor schema version (starts at 1)
	TotalCost         float64   `protobuf:"fixed64,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`                             // root node Total Cost
	ActualTotalTimeMs float64   `protobuf:"fixed64,5,opt,name=actual_total_time_ms,json=actualTotalTimeMs,proto3" json:"actual_total_time_ms,omitempty"` // root node Actual Total Time (0 if not ANALYZE)
	Root              *PlanNode `protobuf:"bytes,6,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueryPlan) Reset() {
	*x = QueryPlan{}
	mi := &file_proto_lynceus_v1_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPlan) ProtoMessage() {}

func (x *QueryPlan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lynceus_v1_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPlan.ProtoReflect.Descriptor instead.
func (*QueryPlan) Descriptor() ([]byte, []int) {
	return file_proto_lynceus_v1_plan_proto_rawDescGZIP(), []int{0}
}

func (x *QueryPlan) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *QueryPlan) GetCapturedAtUnix() int64 {
	if x != nil {
		return x.CapturedAtUnix
	}
	return 0
}

func (x *QueryPlan) GetFormatVersion() int32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *QueryPlan) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *QueryPlan) GetActualTotalTimeMs() float64 {
	if x != nil {
		return x.ActualTotalTimeMs
	}
	return 0
}

func (x *QueryPlan) GetRoot() *PlanNode {
	if x != nil {
		return x.Root
	}
	return nil
}

// PlanNode is one node in the plan tree. Recursive via `plans`.
//
// INVARIANT: every string field is either a structural identifier (node
// type, relation/index name, alias, join type, scan direction) or a
// condition that has already been normalized literal-free. Raw Output and
// Query Text are dropped during extraction and have no field here.
type PlanNode struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NodeType            string                 `protobuf:"bytes,1,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`                // "Seq Scan", "Index Scan", "Hash Join", ...
	RelationName        string                 `protobuf:"bytes,2,opt,name=relation_name,json=relationName,proto3" json:"relation_name,omitempty"`    // table, if any
	IndexName           string                 `protobuf:"bytes,3,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`             // index, if any
	Alias               string                 `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`                                      // range-table alias (identifier, not a literal)
	JoinType            string                 `protobuf:"bytes,5,opt,name=join_type,json=joinType,proto3" json:"join_type,omitempty"`                // "Inner" | "Left" | ...; "" if not a join
	ScanDirection       string                 `protobuf:"bytes,6,opt,name=scan_direction,json=scanDirection,proto3" json:"scan_direction,omitempty"` // "Forward" | "Backward" | ""
	StartupCost         float64                `protobuf:"fixed64,7,opt,name=startup_cost,json=startupCost,proto3" json:"startup_cost,omitempty"`
	TotalCost           float64                `protobuf:"fixed64,8,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	PlanRows            int64                  `protobuf:"varint,9,opt,name=plan_rows,json=planRows,proto3" json:"plan_rows,omitempty"`
	PlanWidth           int32                  `protobuf:"varint,10,opt,name=plan_width,json=planWidth,proto3" json:"plan_width,omitempty"`
	ActualStartupTimeMs float64                `protobuf:"fixed64,11,opt,name=actual_startup_time_ms,json=actualStartupTimeMs,proto3" json:"actual_startup_time_ms,omitempty"` // 0 unless ANALYZE
	ActualTotalTimeMs   float64                `protobuf:"fixed64,12,opt,name=actual_total_time_ms,json=actualTotalTimeMs,proto3" json:"actual_total_time_ms,omitempty"`
	ActualRows          int64                  `protobuf:"varint,13,opt,name=actual_rows,json=actualRows,proto3" json:"actual_rows,omitempty"`
	ActualLoops         int64                  `protobuf:"varint,14,opt,name=actual_loops,json=actualLoops,proto3" json:"actual_loops,omitempty"`
	// Filter / Index Cond / Hash Cond / Join Filter / Recheck Cond, AFTER
	// normalization (literals -> $n). Empty if the source condition could not
	// be proven literal-free — fail closed, never ship a raw predicate.
	NormalizedCondition string `protobuf:"bytes,15,opt,name=normalized_condition,json=normalizedCondition,proto3" json:"normalized_condition,omitempty"`
	// Rows the node read then discarded via its Filter, per loop (Postgres
	// "Rows Removed by Filter"). A COUNT, never a literal — used by the Slow
	// Scan insight to measure scan selectivity. 0 if absent / no ANALYZE.
	RowsRemovedByFilter int64 `protobuf:"varint,17,opt,name=rows_removed_by_filter,json=rowsRemovedByFilter,proto3" json:"rows_removed_by_filter,omitempty"`
	// Sort node spill telemetry (auto_explain "Sort Method"/"Sort Space Type"/
	// "Sort Space Used"). Enum-like labels + a kB COUNT — never a literal. Used
	// by the Disk Sort insight. Empty / 0 when the node is not a Sort or had no
	// ANALYZE actuals.
	SortMethod      string `protobuf:"bytes,18,opt,name=sort_method,json=sortMethod,proto3" json:"sort_method,omitempty"`            // "quicksort" | "top-N heapsort" | "external merge" | "external sort"
	SortSpaceType   string `protobuf:"bytes,19,opt,name=sort_space_type,json=sortSpaceType,proto3" json:"sort_space_type,omitempty"` // "Memory" | "Disk"
	SortSpaceUsedKb int64  `protobuf:"varint,20,opt,name=sort_space_used_kb,json=sortSpaceUsedKb,proto3" json:"sort_space_used_kb,omitempty"`
	// Hash node spill telemetry (auto_explain "Hash Batches"/"Original Hash
	// Batches"/"Peak Memory Usage"). COUNTS only. Used by the Hash Batches
	// insight. 0 when the node is not a Hash.
	HashBatches         int64       `protobuf:"varint,21,opt,name=hash_batches,json=hashBatches,proto3" json:"hash_batches,omitempty"`
	OriginalHashBatches int64       `protobuf:"varint,22,opt,name=original_hash_batches,json=originalHashBatches,proto3" json:"original_hash_batches,omitempty"`
	PeakMemoryUsageKb   int64       `protobuf:"varint,23,opt,name=peak_memory_usage_kb,json=peakMemoryUsageKb,proto3" json:"peak_memory_usage_kb,omitempty"`
	Plans               []*PlanNode `protobuf:"bytes,16,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlanNode) Reset() {
	*x = PlanNode{}
	mi := &file_proto_lynceus_v1_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanNode) ProtoMessage() {}

func (x *PlanNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lynceus_v1_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanNode.ProtoReflect.Descriptor instead.
func (*PlanNode) Descriptor() ([]byte, []int) {
	return file_proto_lynceus_v1_plan_proto_rawDescGZIP(), []int{1}
}

func (x *PlanNode) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *PlanNode) GetRelationName() string {
	if x != nil {
		return x.RelationName
	}
	return ""
}

func (x *PlanNode) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *PlanNode) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *PlanNode) GetJoinType() string {
	if x != nil {
		return x.JoinType
	}
	return ""
}

func (x *PlanNode) GetScanDirection() string {
	if x != nil {
		return x.ScanDirection
	}
	return ""
}

func (x *PlanNode) GetStartupCost() float64 {
	if x != nil {
		return x.StartupCost
	}
	return 0
}

func (x *PlanNode) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *PlanNode) GetPlanRows() int64 {
	if x != nil {
		return x.PlanRows
	}
	return 0
}

func (x *PlanNode) GetPlanWidth() int32 {
	if x != nil {
		return x.PlanWidth
	}
	return 0
}

func (x *PlanNode) GetActualStartupTimeMs() float64 {
	if x != nil {
		return x.ActualStartupTimeMs
	}
	return 0
}

func (x *PlanNode) GetActualTotalTimeMs() float64 {
	if x != nil {
		return x.ActualTotalTimeMs
	}
	return 0
}

func (x *PlanNode) GetActualRows() int64 {
	if x != nil {
		return x.ActualRows
	}
	return 0
}

func (x *PlanNode) GetActualLoops() int64 {
	if x != nil {
		return x.ActualLoops
	}
	return 0
}

func (x *PlanNode) GetNormalizedCondition() string {
	if x != nil {
		return x.NormalizedCondition
	}
	return ""
}

func (x *PlanNode) GetRowsRemovedByFilter() int64 {
	if x != nil {
		return x.RowsRemovedByFilter
	}
	return 0
}

func (x *PlanNode) GetSortMethod() string {
	if x != nil {
		return x.SortMethod
	}
	return ""
}

func (x *PlanNode) GetSortSpaceType() string {
	if x != nil {
		return x.SortSpaceType
	}
	return ""
}

func (x *PlanNode) GetSortSpaceUsedKb() int64 {
	if x != nil {
		return x.SortSpaceUsedKb
	}
	return 0
}

func (x *PlanNode) GetHashBatches() int64 {
	if x != nil {
		return x.HashBatches
	}
	return 0
}

func (x *PlanNode) GetOriginalHashBatches() int64 {
	if x != nil {
		return x.OriginalHashBatches
	}
	return 0
}

func (x *PlanNode) GetPeakMemoryUsageKb() int64 {
	if x != nil {
		return x.PeakMemoryUsageKb
	}
	return 0
}

func (x *PlanNode) GetPlans() []*PlanNode {
	if x != nil {
		return x.Plans
	}
	return nil
}

var File_proto_lynceus_v1_plan_proto protoreflect.FileDescriptor

const file_proto_lynceus_v1_plan_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/lynceus/v1/plan.proto\x12\n" +
	"lynceus.v1\"\xf8\x01\n" +
	"\tQueryPlan\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12(\n" +
	"\x10captured_at_unix\x18\x02 \x01(\x03R\x0ecapturedAtUnix\x12%\n" +
	"\x0eformat_version\x18\x03 \x01(\x05R\rformatVersion\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x04 \x01(\x01R\ttotalCost\x12/\n" +
	"\x14actual_total_time_ms\x18\x05 \x01(\x01R\x11actualTotalTimeMs\x12(\n" +
	"\x04root\x18\x06 \x01(\v2\x14.lynceus.v1.PlanNodeR\x04root\"\xff\x06\n" +
	"\bPlanNode\x12\x1b\n" +
	"\tnode_type\x18\x01 \x01(\tR\bnodeType\x12#\n" +
	"\rrelation_name\x18\x02 \x01(\tR\frelationName\x12\x1d\n" +
	"\n" +
	"index_name\x18\x03 \x01(\tR\tindexName\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12\x1b\n" +
	"\tjoin_type\x18\x05 \x01(\tR\bjoinType\x12%\n" +
	"\x0escan_direction\x18\x06 \x01(\tR\rscanDirection\x12!\n" +
	"\fstartup_cost\x18\a \x01(\x01R\vstartupCost\x12\x1d\n" +
	"\n" +
	"total_cost\x18\b \x01(\x01R\ttotalCost\x12\x1b\n" +
	"\tplan_rows\x18\t \x01(\x03R\bplanRows\x12\x1d\n" +
	"\n" +
	"plan_width\x18\n" +
	" \x01(\x05R\tplanWidth\x123\n" +
	"\x16actual_startup_time_ms\x18\v \x01(\x01R\x13actualStartupTimeMs\x12/\n" +
	"\x14actual_total_time_ms\x18\f \x01(\x01R\x11actualTotalTimeMs\x12\x1f\n" +
	"\vactual_rows\x18\r \x01(\x03R\n" +
	"actualRows\x12!\n" +
	"\factual_loops\x18\x0e \x01(\x03R\vactualLoops\x121\n" +
	"\x14normalized_condition\x18\x0f \x01(\tR\x13normalizedCondition\x123\n" +
	"\x16rows_removed_by_filter\x18\x11 \x01(\x03R\x13rowsRemovedByFilter\x12\x1f\n" +
	"\vsort_method\x18\x12 \x01(\tR\n" +
	"sortMethod\x12&\n" +
	"\x0fsort_space_type\x18\x13 \x01(\tR\rsortSpaceType\x12+\n" +
	"\x12sort_space_used_kb\x18\x14 \x01(\x03R\x0fsortSpaceUsedKb\x12!\n" +
	"\fhash_batches\x18\x15 \x01(\x03R\vhashBatches\x122\n" +
	"\x15original_hash_batches\x18\x16 \x01(\x03R\x13originalHashBatches\x12/\n" +
	"\x14peak_memory_usage_kb\x18\x17 \x01(\x03R\x11peakMemoryUsageKb\x12*\n" +
	"\x05plans\x18\x10 \x03(\v2\x14.lynceus.v1.PlanNodeR\x05plansBAZ?github.com/dobbo-ca/lynceus/internal/proto/lynceus/v1;lynceusv1b\x06proto3"

var (
	file_proto_lynceus_v1_plan_proto_rawDescOnce sync.Once
	file_proto_lynceus_v1_plan_proto_rawDescData []byte
)

func file_proto_lynceus_v1_plan_proto_rawDescGZIP() []byte {
	file_proto_lynceus_v1_plan_proto_rawDescOnce.Do(func() {
		file_proto_lynceus_v1_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lynceus_v1_plan_proto_rawDesc), len(file_proto_lynceus_v1_plan_proto_rawDesc)))
	})
	return file_proto_lynceus_v1_plan_proto_rawDescData
}

var file_proto_lynceus_v1_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_lynceus_v1_plan_proto_goTypes = []any{
	(*QueryPlan)(nil), // 0: lynceus.v1.QueryPlan
	(*PlanNode)(nil),  // 1: lynceus.v1.PlanNode
}
var file_proto_lynceus_v1_plan_proto_depIdxs = []int32{
	1, // 0: lynceus.v1.QueryPlan.root:type_name -> lynceus.v1.PlanNode
	1, // 1: lynceus.v1.PlanNode.plans:type_name -> lynceus.v1.PlanNode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_lynceus_v1_plan_proto_init() }
func file_proto_lynceus_v1_plan_proto_init() {
	if File_proto_lynceus_v1_plan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lynceus_v1_plan_proto_rawDesc), len(file_proto_lynceus_v1_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_lynceus_v1_plan_proto_goTypes,
		DependencyIndexes: file_proto_lynceus_v1_plan_proto_depIdxs,
		MessageInfos:      file_proto_lynceus_v1_plan_proto_msgTypes,
	}.Build()
	File_proto_lynceus_v1_plan_proto = out.File
	file_proto_lynceus_v1_plan_proto_goTypes = nil
	file_proto_lynceus_v1_plan_proto_depIdxs = nil
}
