// Lynceus T1 wire contract.
//
// This file is the SOURCE OF TRUTH for the Lynceus privacy guarantee:
// every field on every T1 message must be a normalized identifier, a
// fingerprint, or an aggregate metric — never a per-execution literal,
// raw query sample, parameter value, or other content that could carry
// PII / PHI / customer data.
//
// Any field that *could* carry literal-bearing content belongs in a
// separate T2 message type (to be defined in its own file), gated
// behind RBAC + audit. T2 capture is opt-in per server and every read
// is recorded in the audit log.
//
// A contract test in internal/proto/lynceus/v1/contract_test.go
// enforces the literal-free invariant for QueryStat. Update the
// allowlist there whenever you legitimately add a normalized field.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/lynceus/v1/snapshot.proto

package lynceusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Snapshot is the unit of telemetry transmitted by a collector for a
// single monitored Postgres server at a single point in time.
type Snapshot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerId        string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CollectedAtUnix int64                  `protobuf:"varint,2,opt,name=collected_at_unix,json=collectedAtUnix,proto3" json:"collected_at_unix,omitempty"`
	QueryStats      []*QueryStat           `protobuf:"bytes,3,rep,name=query_stats,json=queryStats,proto3" json:"query_stats,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_proto_lynceus_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lynceus_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_proto_lynceus_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Snapshot) GetCollectedAtUnix() int64 {
	if x != nil {
		return x.CollectedAtUnix
	}
	return 0
}

func (x *Snapshot) GetQueryStats() []*QueryStat {
	if x != nil {
		return x.QueryStats
	}
	return nil
}

// QueryStat is one row of per-fingerprint query statistics, derived
// from pg_stat_statements and normalized at the collector.
//
// INVARIANT: every field below is either a stable fingerprint, a
// literal-free string, or an aggregate metric. Adding any other kind
// of field violates the T1 privacy guarantee and will fail the
// contract test.
type QueryStat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable hash of the normalized query, suitable as a join key.
	Fingerprint string `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// The query with all literals replaced by positional placeholders
	// (e.g. "SELECT * FROM users WHERE id = $1"). Produced by the
	// collector's pg_query-based normalizer. NEVER contains literal
	// values from the monitored database.
	NormalizedQuery string `protobuf:"bytes,2,opt,name=normalized_query,json=normalizedQuery,proto3" json:"normalized_query,omitempty"`
	// Aggregate metrics from pg_stat_statements.
	Calls          int64   `protobuf:"varint,3,opt,name=calls,proto3" json:"calls,omitempty"`
	TotalTimeMs    float64 `protobuf:"fixed64,4,opt,name=total_time_ms,json=totalTimeMs,proto3" json:"total_time_ms,omitempty"`
	MeanTimeMs     float64 `protobuf:"fixed64,5,opt,name=mean_time_ms,json=meanTimeMs,proto3" json:"mean_time_ms,omitempty"`
	Rows           int64   `protobuf:"varint,6,opt,name=rows,proto3" json:"rows,omitempty"`
	SharedBlksHit  int64   `protobuf:"varint,7,opt,name=shared_blks_hit,json=sharedBlksHit,proto3" json:"shared_blks_hit,omitempty"`
	SharedBlksRead int64   `protobuf:"varint,8,opt,name=shared_blks_read,json=sharedBlksRead,proto3" json:"shared_blks_read,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryStat) Reset() {
	*x = QueryStat{}
	mi := &file_proto_lynceus_v1_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStat) ProtoMessage() {}

func (x *QueryStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lynceus_v1_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStat.ProtoReflect.Descriptor instead.
func (*QueryStat) Descriptor() ([]byte, []int) {
	return file_proto_lynceus_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *QueryStat) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *QueryStat) GetNormalizedQuery() string {
	if x != nil {
		return x.NormalizedQuery
	}
	return ""
}

func (x *QueryStat) GetCalls() int64 {
	if x != nil {
		return x.Calls
	}
	return 0
}

func (x *QueryStat) GetTotalTimeMs() float64 {
	if x != nil {
		return x.TotalTimeMs
	}
	return 0
}

func (x *QueryStat) GetMeanTimeMs() float64 {
	if x != nil {
		return x.MeanTimeMs
	}
	return 0
}

func (x *QueryStat) GetRows() int64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *QueryStat) GetSharedBlksHit() int64 {
	if x != nil {
		return x.SharedBlksHit
	}
	return 0
}

func (x *QueryStat) GetSharedBlksRead() int64 {
	if x != nil {
		return x.SharedBlksRead
	}
	return 0
}

var File_proto_lynceus_v1_snapshot_proto protoreflect.FileDescriptor

const file_proto_lynceus_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/lynceus/v1/snapshot.proto\x12\n" +
	"lynceus.v1\"\x8b\x01\n" +
	"\bSnapshot\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12*\n" +
	"\x11collected_at_unix\x18\x02 \x01(\x03R\x0fcollectedAtUnix\x126\n" +
	"\vquery_stats\x18\x03 \x03(\v2\x15.lynceus.v1.QueryStatR\n" +
	"queryStats\"\x9a\x02\n" +
	"\tQueryStat\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12)\n" +
	"\x10normalized_query\x18\x02 \x01(\tR\x0fnormalizedQuery\x12\x14\n" +
	"\x05calls\x18\x03 \x01(\x03R\x05calls\x12\"\n" +
	"\rtotal_time_ms\x18\x04 \x01(\x01R\vtotalTimeMs\x12 \n" +
	"\fmean_time_ms\x18\x05 \x01(\x01R\n" +
	"meanTimeMs\x12\x12\n" +
	"\x04rows\x18\x06 \x01(\x03R\x04rows\x12&\n" +
	"\x0fshared_blks_hit\x18\a \x01(\x03R\rsharedBlksHit\x12(\n" +
	"\x10shared_blks_read\x18\b \x01(\x03R\x0esharedBlksReadBAZ?github.com/dobbo-ca/lynceus/internal/proto/lynceus/v1;lynceusv1b\x06proto3"

var (
	file_proto_lynceus_v1_snapshot_proto_rawDescOnce sync.Once
	file_proto_lynceus_v1_snapshot_proto_rawDescData []byte
)

func file_proto_lynceus_v1_snapshot_proto_rawDescGZIP() []byte {
	file_proto_lynceus_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_proto_lynceus_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lynceus_v1_snapshot_proto_rawDesc), len(file_proto_lynceus_v1_snapshot_proto_rawDesc)))
	})
	return file_proto_lynceus_v1_snapshot_proto_rawDescData
}

var file_proto_lynceus_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_lynceus_v1_snapshot_proto_goTypes = []any{
	(*Snapshot)(nil),  // 0: lynceus.v1.Snapshot
	(*QueryStat)(nil), // 1: lynceus.v1.QueryStat
}
var file_proto_lynceus_v1_snapshot_proto_depIdxs = []int32{
	1, // 0: lynceus.v1.Snapshot.query_stats:type_name -> lynceus.v1.QueryStat
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_lynceus_v1_snapshot_proto_init() }
func file_proto_lynceus_v1_snapshot_proto_init() {
	if File_proto_lynceus_v1_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lynceus_v1_snapshot_proto_rawDesc), len(file_proto_lynceus_v1_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_lynceus_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_proto_lynceus_v1_snapshot_proto_depIdxs,
		MessageInfos:      file_proto_lynceus_v1_snapshot_proto_msgTypes,
	}.Build()
	File_proto_lynceus_v1_snapshot_proto = out.File
	file_proto_lynceus_v1_snapshot_proto_goTypes = nil
	file_proto_lynceus_v1_snapshot_proto_depIdxs = nil
}
